"""Add lesson_summary, skill_set, diagnostic, groups, teaching_pack_data columns to teaching_packs table

Revision ID: 2675e2c05b2a
Revises: 6d50d4d53f10
Create Date: 2026-01-13 02:08:53.057014+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2675e2c05b2a'
down_revision: Union[str, Sequence[str], None] = '6d50d4d53f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaching_packs', sa.Column('lesson_summary', sa.JSON(), nullable=True))
    op.add_column('teaching_packs', sa.Column('skill_set', sa.JSON(), nullable=True))
    op.add_column('teaching_packs', sa.Column('diagnostic', sa.JSON(), nullable=True))
    op.add_column('teaching_packs', sa.Column('teaching_pack_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaching_packs', 'teaching_pack_data')
    op.drop_column('teaching_packs', 'diagnostic')
    op.drop_column('teaching_packs', 'skill_set')
    op.drop_column('teaching_packs', 'lesson_summary')
    # ### end Alembic commands ###
