"""add flashcard_urls to teaching_packs

Revision ID: 3ba0ffddfe80
Revises: 2b3c4d5e6f7a
Create Date: 2026-01-18 12:47:37.674329+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba0ffddfe80'
down_revision: Union[str, Sequence[str], None] = '2b3c4d5e6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaching_packs', sa.Column('flashcard_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaching_packs', 'flashcard_urls')
    # ### end Alembic commands ###
