"""Add uploaded_by_id to lessons table

Revision ID: acfa7cf5904b
Revises: 9229b4cac7c2
Create Date: 2026-01-09 15:44:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfa7cf5904b'
down_revision: Union[str, None] = '9229b4cac7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_lessons_uploaded_by_id_users', 'users', ['uploaded_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lessons_uploaded_by_id_users', type_='foreignkey')
        batch_op.drop_column('uploaded_by_id')

    # ### end Alembic commands ###