"""Make classroom_id nullable for teaching_packs

Revision ID: c0ab1f3702cc
Revises: d5111a331fcb
Create Date: 2026-01-10 02:40:04.875820+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ab1f3702cc'
down_revision: Union[str, Sequence[str], None] = 'd5111a331fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('uploaded_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teaching_packs', schema=None) as batch_op:
        batch_op.alter_column('classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_packs', schema=None) as batch_op:
        batch_op.alter_column('classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('uploaded_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
