"""Make classroom_id nullable for lessons

Revision ID: d5111a331fcb
Revises: 2cadae36416a
Create Date: 2026-01-10 02:33:20.078089+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5111a331fcb'
down_revision: Union[str, Sequence[str], None] = '2cadae36416a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
